# adds firewalls to a server dependent on what is running
- name: add firewalls
  block:

    - name: Part of the trusted set of servers
      include: tasks/_firewall_trusted_network.yml
      when: trusted_host is defined and trusted_host == 'yes'

    #      firewalld:
    #        source: "{{galaxy_ip}}"
    #        permanent: true
    #        state: enabled
    #        #        immediate: yes
    #        zone: trusted
    #      loop: "{{ groups['all'] }}"

    - name: systemd start of firewalld
      systemd:
        state: started
        enabled: yes
        name: firewalld


    - name: "collect host information"
      package_facts:
        manager: "auto"


    - name: ssh firewall setup (always open)
      firewalld:
        service: ssh
        permanent: true
#        immediate: yes
        state: enabled
        zone: external


    - name: https firewall setup
      firewalld:
        service: https
        permanent: true
#        immediate: yes
        state: enabled
        zone: external
      when: "'nginx' in ansible_facts.packages or 'httpd' in ansible_facts.packages"

    - name: http firewall setup
      firewalld:
        service: http
        permanent: true
#        immediate: yes
        state: enabled
        zone: external
      when: "'nginx' in ansible_facts.packages or 'httpd' in ansible_facts.packages"

    - name: rabbitmq firewall setup
      firewalld:
        port: 5671-5672/tcp # 5672 is amqps
        permanent: true
        state: enabled
#        immediate: yes
        zone: external
      when: "'rabbitmq-server' in ansible_facts.packages"


    - name: postgres firewall setup
      firewalld:
        service: postgres
        permanent: true
        state: enabled
#        immediate: yes
        zone: external
      when: "False and 'postgresql10-server' in ansible_facts.packages"







