---
# GDPR specific logrotations.
- name: setup usegalaxy.no specific logrotates
  block:

    - name: "collect host information"
      package_facts:
        manager: "auto"
    
    - name: install gpg package
      yum:
        name: gnupg2
        state: present
        update_cache: yes
    
    - name: copy gpg keygen file
      template:
        src: files/system/gpg-genkey.j2
        dest: /root/gpg-genkey
    
    - name: create gpg key
      command: gpg2 --batch --gen-key /root/gpg-genkey
    
    - name: delete gpg genkey file
      file:
        path: /root/gpg-genkey
        state: absent

    - name: "nginx logrotate"
      template:
        src: files/system/logrotate.nginx
        dest: /etc/logrotate.d/nginx
        mode: 0644
        owner: root
        group: root
        backup: yes
      when: "'nginx' in ansible_facts.packages"


    - name: check for galaxy installataion
      stat:
        path: "{{galaxy_root}}"
      register: galaxy_installation

    - name: "copy logrotate.conf"
      template:
        src: files/system/logrotate.conf
        dest: /etc/logrotate.conf
        mode: 0644
        owner: root
        group: root
        backup: yes
      when: galaxy_installation.stat.isdir

    - name: "messages logrotate"
      template:
        src: files/system/logrotate.syslog
        dest: /etc/logrotate.d/syslog
        mode: 0644
        owner: root
        group: root
        backup: yes
      when: galaxy_installation.stat.isdir

