---
#setup for rabbit mq
- name: Setup rabbitmq


  block:

  - name: Remove default guest user
    rabbitmq_user: user=guest state=absent

  - name: Enables the rabbitmq_management plugin
    rabbitmq_plugin:
      names: rabbitmq_management
      state: enabled

  - name: Create vhosts
    rabbitmq_vhost: name=/{{item}} state=present
    with_items:
      - "{{rabbitmq_vhosts}}"

  - name: Add users
    rabbitmq_user: user={{ item.name }} password={{ item.passwd }} tags={{ item.tags | default(item.name)}} vhost=/{{ item.vhost }} configure_priv=".*" write_priv=".*" read_priv=".*" state=present
    with_items:
      - "{{rabbitmq_users}}"

#  - name: rabbitmq config stats
#    stat:
#      path: templates/rabbitmq/rabbitmq.j2
#    register: rabbitmq_config

  - name: Copy rabbitmq file
    template:
      src: templates/rabbitmq/rabbitmq.j2
      dest: /etc/rabbitmq/rabbitmq.conf
    notify:
      - restart rabbitmq
#    when: rabbitmq_config.stat.exists == True
#
  - name: Copy cert files 
    copy:
      src: "/etc/letsencrypt/live/{{ inventory_hostname }}/{{ item }}"
      dest: /etc/rabbitmq/
      remote_src: yes
      owner: rabbitmq
      group: rabbitmq
      mode: 0600
    with_items:
      - cert.pem
      - fullchain.pem
      - privkey.pem
