- name: Add NeLS storage IDs to known_hosts
  become: true
  become_user: "{{ galaxy_user.name }}"
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key }}"  # some key gibberish
    state: present
  with_items: " {{ ssh_known_hosts }}"