postgresql_databases:
  - name: "{{galaxy_database}}"
#    login_host: "{{galaxy_host}}"
#    login_password: "{{galaxy_db_passwd}}"
#     login_user: "{{galaxy_db_user}}"
#    login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
    owner: "{{galaxy_db_user}}"

postgresql_users:
  - name: "{{galaxy_db_user}}"
    password: "{{galaxy_db_passwd}}"

# Host based authentication (hba) entries to be added to the pg_hba.conf. This
# variable's defaults reflect the defaults that come with a fresh installation.
postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
# Makes it possible for the galaxy-db use to connect both from localhost and the galaxy-host (ip based
  - {type: local, database: "{{galaxy_database}}", user: "{{galaxy_db_user}}", auth_method: md5}
  - {type: host, database: "{{galaxy_database}}", user: "{{galaxy_db_user}}", address: "{{galaxy_ip}}/0", auth_method: md5}
# This is needed to ensure that the database exists and comes from sqlalchemy not the galaxy code!
  - {type: host, database: "postgres", user: "{{galaxy_db_user}}", address: "{{galaxy_ip}}/0", auth_method: md5}
# If encryptions between galaxy and post is needed
#  - {type: hostssl, database: "{{galaxy_database}}", user: "{{galaxy_db_user}}", address: "{{galaxy_ip}}/0", auth_method: md5}

postgresql_global_config_options:
  - option: listen_addresses
    value: '*'
#  - option: ssl
#    value: "on"
#  - option: ssl_cert_file
#    value: "{{ssl_cert}}"
#  - option: ssl_key_file
#    value: "{{ssl_key}}"



