slurm_cgroup_config:
  CgroupMountpoint: "/sys/fs/cgroup"
  CgroupAutomount: yes
  ConstrainCores: yes
  TaskAffinity: no
  ConstrainRAMSpace: no
  ConstrainSwapSpace: no
  ConstrainDevices: no
  AllowedRamSpace: 100
  AllowedSwapSpace: 0
  MaxRAMPercent: 100
  MaxSwapPercent: 100
  MinRAMSpace: 30
slurm_config:
  ClusterName: "usegalaxy_{{ env }}"
  SchedulerType: sched/backfill
  TaskPlugin: task/affinity,task/cgroup
  TaskPluginParam: Sched
  SelectType: select/cons_res
  ProctrackType: proctrack/cgroup
  JobAcctGatherType: jobacct_gather/cgroup
  AccountingStorageType: accounting_storage/slurmdbd
  SelectTypeParameters: CR_Core_Memory
  ControlMachine: "{{ galaxy_host }}"
  SlurmctldLogFile: /var/log/slurm/slurmctld.log
  SlurmdLogFile: /var/log/slurm/slurmd.log
  SlurmdDebug: 3
  DefMemPerCPU: 1000
slurmdbd_config:
  AuthType: auth/munge
  DbdAddr: "{{ hostvars[galaxy_host].ansible_hostname }}"
  DbdHost: "{{ hostvars[galaxy_host].ansible_hostname }}"
  LogFile: /var/log/slurm/slurmdbd.log
  PidFile: /var/run/slurmdbd.pid
  StorageType: accounting_storage/mysql
  StorageHost: " {{ db_host }}"
  StoragePort: 3306
  StoragePass: "{{ mysql_slurm_password }}"
  StorageUser: "{{ mysql_slurm_username }}"
  StorageLoc: slurm_acct_db
slurm_nodes:
  - name: "{{ hostvars[galaxy_host].ansible_hostname }}"
    CoresPerSocket: "{{ hostvars[galaxy_host].ansible_processor_cores }}"
    Sockets: "{{ hostvars[galaxy_host].ansible_processor_count }}"
    ThreadsPerCore: "{{ hostvars[galaxy_host].ansible_processor_threads_per_core }}"
    CPUs: "{{ hostvars[galaxy_host].ansible_processor_vcpus }}"
    RealMemory: "{{ hostvars[galaxy_host].ansible_memtotal_mb }}"
  - name: "{{ hostvars[slurm_host].ansible_hostname }}"
    CoresPerSocket: "{{ hostvars[slurm_host].ansible_processor_cores }}"
    Sockets: "{{ hostvars[slurm_host].ansible_processor_count }}"
    ThreadsPerCore: "{{ hostvars[slurm_host].ansible_processor_threads_per_core }}"
    CPUs: "{{ hostvars[slurm_host].ansible_processor_vcpus }}"
    RealMemory: "{{ hostvars[slurm_host].ansible_memtotal_mb }}"
slurm_partitions:
  - name: "usegalaxy_{{ env }}"
    Default: YES
    MaxTime: UNLIMITED
    Nodes: "{{ hostvars[slurm_host].ansible_hostname }}"

slurm_munge_key: files/munge/munge.key

slurm_node_ips: "{{ groups['slurm'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }}"

nfs_exports:
  - path: "/srv/galaxy"
    export: "{{ slurm_node_ips }}(rw,async,no_root_squash)"
  - path: "/data"
    export: "{{ slurm_node_ips }}(rw,sync,no_root_squash)"

nfs_client_imports:
  - local: "/srv/galaxy"
    remote: "/srv/galaxy"
    server_host: "{{ galaxy_host }}"
  - local: "/data"
    remote: "/data"
    server_host: "{{ galaxy_host }}"

cvmfs_role: client
galaxy_cvmfs_repos_enabled: config-repo
cvmfs_quota_limit: 6000
cvmfs_server_urls:
  - domain: galaxyproject.org
    use_geoapi: no
    urls:
      - "http://invivo.hpc.uio.no/cvmfs/@fqrn@"
      - "http://cvmfs1-ufr0.galaxyproject.eu/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-mel0.gvl.org.au/cvmfs/@fqrn@"
  - domain: "{{ galaxy_host }}"
    use_geoapi: no
    urls:
      - "http://{{ cvmfs0_host }}/cvmfs/@fqrn@"
cvmfs_keys:
  - path: "/etc/cvmfs/keys/{{ galaxy_host }}/data.{{ galaxy_host }}.pub"
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAumGVOoY9O9B9J2A2n82A
      OhewmxGt4JXOryMc2gIfjyb2K2hIxPxoDtqxaj4QZx4lLge+Y4WyCAiz/5v8m+Ef
      Pprx+rxrXzuXAi0lfYNL1+1lUUrOPpRvn0fnzMC+2cb52gchVYjZEK0i5N1ctoV3
      DjUol5rawBtAXZ1z8RF4352idAyt9D5KMZ13X12cxR2Rw8F/dQzL2MkuplvwQKpU
      zNt0jbIlwbCWovkEKi5kaZIrn9d7yoIMIbabdOH4HtMxUX7wlH9Qlpr23Y1iVe5Y
      8ZqKZKV/stlhgpGCsolyyg1GDcKL0H7ysk8J03cqIgznmfe+MdWo4oGU6wgvAq+B
      oQIDAQAB
      -----END PUBLIC KEY-----

