- hosts: database
  become: true
  tags:
    - database

  vars_files:
    - group_vars/global.yml
    - group_vars/database.yml
    - group_vars/certbot.yml
    - group_vars/rabbitmq.vault
    - group_vars/rabbitmq_proxy.yml

  handlers:
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted

  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['epel-release', 'python3']

  tasks:
    - name: Setup ssh access
      become: false
      include: tasks/keys.yml
    - name: setup rabbitmq certs, vhosts and users
      include: tasks/rabbitmq.yml

  roles:
    - role: geerlingguy.postgresql
      become: yes
    - geerlingguy.rabbitmq
    - galaxyproject.nginx
 