- hosts: database
  become: true
  tags:
    - database

  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/database.yml
    - group_vars/certbot.yml
    - group_vars/rabbitmq.yml
    - group_vars/rabbitmq_proxy.yml

  handlers:
    - name: restart rabbitmq
      service: name=rabbitmq-server state=restarted

  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['python3', 'python-psycopg2']
    - name: Install Apache dependencies
      package:
         name: ['libproxy', 'mod_proxy_uwsgi']
  tasks:
    - name: Create users and groups
      include: tasks/users_groups.yml
    - name: setup rabbitmq certs, vhosts and users
      include: tasks/rabbitmq.yml

  roles:
    - geerlingguy.repo-epel
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.certbot
    - geerlingguy.rabbitmq
    - geerlingguy.apache