- hosts: galaxyserver
  become: true
  tags:
    - galaxyserver
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/galaxy.yml
    - group_vars/pulsar_nmbu_orion.yml
    - group_vars/slurm.yml
    - group_vars/telegraf.yml

  pre_tasks:
    - name: Install Dependencies
      package:
#        use_backend: dnf
        name:
          - 'epel-release'
          - 'python3'
          - 'python3-psycopg2'
          - 'git'
          - 'python36-virtualenv'
          - 'make'
          - 'bzip2'
          - 'postgresql'
  
  tasks:
    - name: Perform misc tasks
      include: tasks/galaxy.yml

  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted

  roles:
    - geerlingguy.pip
    - galaxyproject.repos
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: galaxy
    - usegalaxy_eu.galaxy_systemd
    - galaxyproject.nginx
    - galaxyproject.cvmfs
    - galaxyproject.repos
    - galaxyproject.slurm
    - dj-wasabi.telegraf
    - geerlingguy.docker
    - usegalaxy_eu.gie_proxy
    - usegalaxy_eu.gxadmin

  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
    # TODO: This should not be needed, but...
    - name: Make sure galaxy owns some files
      file:
        path: "{{ galaxy_root }}/server/tool-data"
        state: directory
        recurse: yes
        mode: '0755'
        owner: "{{ galaxy_user.name }}"
      file:
        path: "{{ galaxy_mutable_config_dir }}/sanitize_whitelist.txt"
        state: file
        mode: '0755'
        owner: "{{ galaxy_user.name }}"
