- hosts: galaxyserver
  become: true
  vars:
    slurm_roles: ['controller', 'exec']
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa

- hosts: slurm
  become: true
  vars:
    slurm_roles: ['exec']
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
