- hosts: galaxyserver
  become: true
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['controller']
    nfs_mode: server
  pre_tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  - name: Add galaxy paths for nfs export
    become: true
    file:
      path: "{{ item }}"
      state: directory
      mode: '0750'
      owner: "{{ galaxy_user.name }}"
      group: "{{ galaxy_user.name }}"
    with_items:
      - "{{ galaxy_file_path }}"
      - "{{ galaxy_root }}"
  - name: Create users and groups
    include: tasks/users_groups.yml
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - indigo-dc.nfs
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
    
- hosts: slurm
  become: true
  vars_files:
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['exec']
    nfs_mode: client
  pre_tasks:
  - name: Create users and groups
    include: tasks/users_groups.yml
  - name: Add users and other tasks
    include: tasks/slurm.yml
  roles:
    - geerlingguy.repo-epel
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - geerlingguy.docker
    - indigo-dc.nfs
  post_tasks:
    - name: Install packages
      package:
        name:
          - 'slurm-drmaa'
          - 'python3'
          - 'git'
          - 'python36-virtualenv'
          - 'bzip2'
