- hosts: galaxyserver
  become: true
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['controller']
    nfs_mode: server
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  - name: Add users and other tasks
    include: tasks/slurm.yml
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - indigo-dc.nfs
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa
    
- hosts: slurm
  become: true
  pre_tasks:
    - name: Install epel
      package:
        name:
          - 'epel-release'
  vars_files:
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['exec']
    nfs_mode: client
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  - name: Add users and other tasks
    include: tasks/slurm.yml
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - geerlingguy.docker
    - indigo-dc.nfs
  post_tasks:
    - name: Install packages
      package:
        name:
          - 'slurm-drmaa'
          - 'epel-release'
          - 'python3'
          - 'git'
          - 'python36-virtualenv'
          - 'bzip2'
