- hosts: galaxyserver
  become: true
  vars_files:
    - group_vars/global.yml
    - group_vars/slurm.yml
  vars:
    slurm_roles: ['controller', 'exec']
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  - name: Copy munge key
    copy:
      src: files/munge/munge.key
      dest: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: '0400'
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa

- hosts: slurm
  become: true
  pre_tasks:
    - name: Install epel
      package:
        name:
          - 'epel-release'
  vars_files:
    - group_vars/global.yml
    - group_vars/slurm.yml
  vars:
    slurm_roles: ['exec']
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  - name: Copy munge key
    copy:
      src: files/munge/munge.key
      dest: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: '0400'
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.cvmfs
  post_tasks:
    - name: Install packages
      package:
        name:
          - 'slurm-drmaa'
          - 'epel-release'
          - 'python3'
          - 'git'
          - 'python36-virtualenv'
          - 'bzip2'
