- hosts: galaxyserver
  become: true
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['controller']
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  - name: Copy slurm telegraf plugin
    copy:
      src: files/telegraf/slurm-collect.sh
      dest: "{{ custom_telegraf_slurm_collect_bin }}"
      owner: root
      group: root
      mode: '0755'
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa

- hosts: slurm
  become: true
  pre_tasks:
    - name: Install epel
      package:
        name:
          - 'epel-release'
  vars_files:
    - group_vars/global.yml
    - group_vars/slurm.yml
    - group_vars/galaxy.yml
  vars:
    slurm_roles: ['exec']
  tasks:
  - name: Setup ssh access
    become: false
    include: tasks/keys.yml
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - geerlingguy.docker

  post_tasks:
    - name: Install packages
      package:
        name:
          - 'slurm-drmaa'
          - 'epel-release'
          - 'python3'
          - 'git'
          - 'python36-virtualenv'
          - 'bzip2'
