- hosts: slurm, galaxyserver, jenkins
  become: true
  vars_files:
  - group_vars/global.yml
  tasks:
  - name: Set timezone to Europe/Oslo
    timezone:
      name: Europe/Oslo
  roles:
    - reallyenglish.dhclient