- hosts: slurm, galaxyserver, jenkins, database
  become: true
  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/telegraf.yml
  tasks:
  - name: Set timezone to Europe/Oslo
    timezone:
      name: Europe/Oslo
  roles:
    - reallyenglish.dhclient
    - nbigot.ansible-fail2ban
    - dj-wasabi.telegraf
    - idiv-biodiversity.postfix
