- hosts: slurm, galaxyserver, jenkins, database, ehos_servers
  become: true

  vars_files:
    - secret_group_vars/global.vault
    - group_vars/global.yml
    - group_vars/telegraf.yml

  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          - 'mailx'
          - 'vim'
          - 'mlocate'
    - name: set hostname
      hostname:
        name: "{{inventory_hostname}}"
  tasks:
    - name: Set timezone to Europe/Oslo
      timezone:
        name: Europe/Oslo
    - name: Setup ssh access
      become: false
      include: tasks/users_groups.yml

  roles:
    - geerlingguy.repo-epel
    - reallyenglish.dhclient
    - nbigot.ansible-fail2ban
    - dj-wasabi.telegraf
    - idiv-biodiversity.postfix
