- hosts: galaxyservers
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['epel-release','python3', 'python-psycopg2', 'git', 'python-virtualenv', 'make', 'bzip2']
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.galaxy
    - uchida.miniconda
    - geerlingguy.pip
    - geerlingguy.nginx
    - usegalaxy-eu.supervisor
  tasks:
    yum:
      name: httpd
      state: latest


