- hosts: galaxyservers
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['epel-release','python3', 'python-psycopg2', 'git', 'python-virtualenv', 'make', 'bzip2']
    - name: "Load variables"
      include_vars: "group_vars/global.yml"
      include_vars: "group_vars/galaxyservers.yml"
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
#    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
#    - geerlingguy.pip
#    - galaxyproject.galaxy
#    - uchida.miniconda
#    - geerlingguy.pip
    - usegalaxy-eu.certbot
    - geerlingguy.nginx
#    - usegalaxy-eu.supervisor
