id: nels_export_history
type:
  - history-menu
activate: true
title: Export History to NeLS II

function: >
  action="export";
  console.log( Galaxy );

  galaxy_instance = window.location.host;
  history_id = Galaxy.currHistoryPanel.model.id;
  user_email = Galaxy.user.attributes.email;

  console.log(galaxy_instance);
  console.log(history_id);
  console.log(user_email);

  galaxy_url=window.location.protocol+"//"+window.location.host;
  galaxy_url+=Galaxy.root;
  console.log('galaxy history export');
  if (!galaxy_url.endsWith("/")) galaxy_url+="/";
  nels_storage_url  = "https://nels.bioinfo.no/welcome.xhtml?GALAXY_URL="+galaxy_url;
  nels_storage_url += "&appCallbackUrl=https://usegalaxy.no/nels-galaxy/export/";
  nels_storage_url += "%3Finstance="+galaxy_instance;
  nels_storage_url += "%26history_id="+history_id;
  nels_storage_url += "%26user="+user_email;

  //nels_storage_url  = "https://nels.bioinfo.no/welcome.xhtml?GALAXY_URL="+galaxy_url;
  nels_storage_url  = "https://nels.bioinfo.no/welcome.xhtml?";
  //nels_storage_url  = "GALAXY_URL="+galaxy_url+"&";
  nels_storage_url += "appCallbackUrl=https://usegalaxy.no/nels-galaxy/export/";
  nels_storage_url += galaxy_instance+"/";
  nels_storage_url += user_email+"/";
  nels_storage_url += history_id+"/";


  console.log(nels_storage_url);

  //window.location.href = nels_storage_url;
