- hosts: galaxyservers
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['epel-release','python3', 'python-psycopg2', 'git', 'python-virtualenv', 'make', 'bzip2']
    - name: "Load variables"
      include_vars: "group_vars/global.yml"
  roles:
    - role: geerlingguy.apache
      become: yes


- hosts: galaxyservers
  become: true
  tags:
    - certs
  vars_files:
    - group_vars/global.yml
    - group_vars/certs.yml
  pre_tasks:
    - name: Stop service httpd, if started
      service:
        name: httpd
        state: stopped
  roles:
    - role: geerlingguy.certbot
      become: yes
  pre_tasks:
    - name: Stop service httpd, if started
      service:
        name: httpd
        state: started


- hosts: galaxyservers
  become: true
  tags:
    - apache
  pre_tasks:
    - name: Install apache dependencies
      package:
        name: ['libproxy', 'mod_proxy_uwsgi']
  vars_files:
    - group_vars/global.yml
    - group_vars/apache.yml
  roles:
    - role: geerlingguy.apache
      become: yes


- hosts: databases
  become: true
  tags:
    - database
  vars_files:
    - group_vars/global.yml
    - group_vars/databases.yml
  roles:
    - role: geerlingguy.postgresql
      become: yes

# This will be used for tweaking the specifics for the galaxy monitoring
- hosts: databases
  become: true
  tags:
    - telegraf
  become: true
  vars_files:
    - group_vars/global.yml
    - group_vars/telegraf.yml
  roles:
    - dj-wasabi.telegraf


# This will be used for tweaking the specifics for the galaxy monitoring
- hosts: galaxyservers
  become: true
  tags:
    - galaxytelegraf
  become: true
  vars_files:
    - group_vars/global.yml
    - group_vars/galaxy_telegraf.yml
  vars:
    galaxy_admin_dir: /usr/local/galaxy_admin
  pre_tasks:
    - name: install galaxy-admin
      git:
        repo: 'https://github.com/elixir-no-nels/galaxy-admin.git'
        dest: "{{galaxy_admin_dir}}"
        force: yes
    - name: setup virtual env
      command: "/bin/python3 -m venv venv"
      args:
        chdir: "{{galaxy_admin_dir}}"
    - name: install requirements
      command: "{{galaxy_admin_dir}}/venv/bin/pip3 install -r {{galaxy_admin_dir}}/requirements.txt"
      args:
        chdir: /usr/local/galaxy-admin/
    - name: Copy config file
      template:
        src: templates/galaxy-admin/galaxy.json.j2
        dest: "{{galaxy_admin_dir}}/galaxy.json"
        force: yes
  roles:
    - dj-wasabi.telegraf


# https://github.com/CSCfi/ansible-role-slurm
#- hosts: galaxyservers
#  strategy: free
#  tags:
#    - slurm
#  roles:
#    - { role: ansible-role-pam }
#    - { role: ansible-role-nhc }
#    - { role: ansible-role-slurm }
#- hosts: install
#  roles:
#    - { role: ansible-role-slurm }
