- hosts: galaxyservers
  gather_facts: False
#  connection: local
  become: true
  become_user: galaxy
  vars_files:
    - group_vars/global.yml
  vars:
    galaxy_tools_tool_list_files: [ "files/tools_list.yml" ]
    galaxy_tools_galaxy_instance_url: "https://{{galaxy_host}}/"
    use_pbkdf2: false
    galaxy_tools_api_key: "{{galaxy_api_key}}"
    admin_email: "{{galaxy_admin}}"
  roles:
    - usegalaxy.galaxy-tools
#  tasks:
#    - name: "Install galaxy user creation script."
#      template: src=roles/usegalaxy.galaxy-extras/templates/create_galaxy_user.py.j2 dest="{{ galaxy_root}}/server/create_galaxy_user.py" mode=a+x
#    - name: "add galaxy admin user"
#      command: "./venv/bin/python  server/create_galaxy_user.py --user  {{ admin_email }}  --password sdfsdfsdf"
#      args:
#        chdir: "{{ galaxy_root }}"
