- hosts: rabbitmq
  become: true

  tasks:
  - name: add users
    rabbitmq_user: user={{item}} password=changeme tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
    with_items:
    - user1
    - user2

  - name: remove default guest user
    rabbitmq_user: user=guest state=absent

  - name: ensure vhost /test is present
    rabbitmq_vhost: name=/test state=present

  handlers:
  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted
